package demo.config;

import cn.zaichi.zmvc.plugin.activerecord.ActiveRecordPlugin;
import demo.model.base.Account;
import demo.model.base.TFile;
import demo.model.base.User;


/**
 * 关联数据库表与pojo类工具类
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_account","id", Account.class);
		arp.addMapping("t_file","id", TFile.class);
	}
}

